# Generated by Django 3.1.4 on 2020-12-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_sent_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
