# Generated by Django 3.1.4 on 2020-12-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_room_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
